# Start from the official Golang image
FROM golang:1.20-alpine AS builder

# Copy the application source code
COPY . /time-tracker-api

# Build the Go Fiber application binary
WORKDIR /time-tracker-api
RUN CGO_ENABLED=0 GOOS=linux go build -o time-tracker-api .

# Use a minimal runtime image
FROM alpine:3.18

# Copy the binary from the builder stage to the runtime image
COPY --from=builder /time-tracker-api/time-tracker-api .

# Command to run the Go Fiber application when the container starts
CMD ["./time-tracker-api"]
