# Start from the official Golang image
FROM golang:1.20-alpine AS builder

# Set the working directory inside the container
WORKDIR /time-tracker

# Copy the Go module files
COPY go.mod go.sum ./

# Download the Go module dependencies
RUN go mod download

# Copy the application source code
COPY . .

# Build the Go Fiber application binary
RUN CGO_ENABLED=0 GOOS=linux go build -o time-tracker .

# Use a minimal runtime image
FROM alpine:3.18

# Set the working directory inside the container
WORKDIR /time-tracker

# Copy the binary from the builder stage to the runtime image
COPY --from=builder /time-tracker/time-tracker .

# Expose the port that the Go Fiber application listens on
EXPOSE 8080

# Command to run the Go Fiber application when the container starts
CMD ["./time-tracker"]
