apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: database-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: database
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: root # Replace with your desired username
            - name: POSTGRES_PASSWORD
              value: password # Replace with your desired password
            - name: POSTGRES_DB
              value: time_tracker_db # Replace with your desired database name
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
